/**
 * @file gfl_vac_ctrl.h
 * @brief Level-5 Park-dq AC-voltage outer loop.
 */

#ifndef _FILE_GFL_VAC_CTRL_H_
#define _FILE_GFL_VAC_CTRL_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <ctl/component/digital_power/inv/gfl_core.h>
#include <ctl/component/intrinsic/basic/slope_limiter.h>

typedef struct _tag_gfl_vac_ctrl
{
    ctl_vector2_t* vdq_meas; //!< RO: Park transformed voltage feedback from inv_ctrl.

    ctl_vector2_t vdq_set;         //!< R/W: Final voltage command.
    ctl_vector2_t vdq_ref;         //!< RO: Slew-limited voltage command.
    ctl_vector2_t vdq_meas_mirror; //!< RO: Mirrored voltage feedback for debugging.
    ctl_vector2_t idq_set_out;     //!< RO: Current reference generated by voltage PI.

    ctl_pid_t pid_vd;
    ctl_pid_t pid_vq;
    ctl_slope_limiter_t vd_ref_limiter;
    ctl_slope_limiter_t vq_ref_limiter;

    ctrl_gt max_i2_mag;
    fast_gt flag_enable;
} gfl_vac_ctrl_t;

GMP_STATIC_INLINE void ctl_init_gfl_vac(gfl_vac_ctrl_t* vac, parameter_gt vd_kp, parameter_gt vd_ki,
                                        parameter_gt vq_kp, parameter_gt vq_ki, parameter_gt i_out_max,
                                        parameter_gt v_ref_slew, parameter_gt fs)
{
    ctrl_gt current_limit = float2ctrl(i_out_max);

    vac->vdq_meas = 0;
    vac->flag_enable = 0;
    vac->max_i2_mag = ctl_mul(current_limit, current_limit);

    ctl_init_pid(&vac->pid_vd, vd_kp, vd_ki, 0, fs);
    ctl_init_pid(&vac->pid_vq, vq_kp, vq_ki, 0, fs);
    ctl_set_pid_limit(&vac->pid_vd, current_limit, -current_limit);
    ctl_set_pid_limit(&vac->pid_vq, current_limit, -current_limit);
    ctl_set_pid_int_limit(&vac->pid_vd, current_limit, -current_limit);
    ctl_set_pid_int_limit(&vac->pid_vq, current_limit, -current_limit);

    ctl_init_slope_limiter(&vac->vd_ref_limiter, v_ref_slew, -v_ref_slew, fs);
    ctl_init_slope_limiter(&vac->vq_ref_limiter, v_ref_slew, -v_ref_slew, fs);

    ctl_vector2_clear(&vac->vdq_set);
    ctl_vector2_clear(&vac->vdq_ref);
    ctl_vector2_clear(&vac->vdq_meas_mirror);
    ctl_vector2_clear(&vac->idq_set_out);
}

GMP_STATIC_INLINE void ctl_clear_gfl_vac(gfl_vac_ctrl_t* vac)
{
    ctl_clear_pid(&vac->pid_vd);
    ctl_clear_pid(&vac->pid_vq);
    ctl_clear_slope_limiter(&vac->vd_ref_limiter);
    ctl_clear_slope_limiter(&vac->vq_ref_limiter);
    ctl_vector2_clear(&vac->vdq_ref);
    ctl_vector2_clear(&vac->vdq_meas_mirror);
    ctl_vector2_clear(&vac->idq_set_out);
    vac->flag_enable = 0;
}

GMP_STATIC_INLINE void ctl_set_gfl_vac_ref(gfl_vac_ctrl_t* vac, ctrl_gt vd_ref, ctrl_gt vq_ref)
{
    vac->vdq_set.dat[phase_d] = vd_ref;
    vac->vdq_set.dat[phase_q] = vq_ref;
}

GMP_STATIC_INLINE void ctl_attach_gfl_vac(gfl_vac_ctrl_t* vac, ctl_vector2_t* vdq)
{
    vac->vdq_meas = vdq;
}

GMP_STATIC_INLINE void ctl_attach_gfl_vac_to_core(gfl_vac_ctrl_t* vac, gfl_inv_ctrl_t* core)
{
    gmp_base_assert(vac);
    gmp_base_assert(core);
    vac->vdq_meas = &core->vdq;
}

GMP_STATIC_INLINE void ctl_step_gfl_vac(gfl_vac_ctrl_t* vac)
{
    if (!vac->vdq_meas)
        return;

    vac->vdq_meas_mirror.dat[phase_d] = vac->vdq_meas->dat[phase_d];
    vac->vdq_meas_mirror.dat[phase_q] = vac->vdq_meas->dat[phase_q];

    if (vac->flag_enable)
    {
        vac->vdq_ref.dat[phase_d] = ctl_step_slope_limiter(&vac->vd_ref_limiter, vac->vdq_set.dat[phase_d]);
        vac->vdq_ref.dat[phase_q] = ctl_step_slope_limiter(&vac->vq_ref_limiter, vac->vdq_set.dat[phase_q]);

        ctrl_gt vd_err = vac->vdq_ref.dat[phase_d] - vac->vdq_meas_mirror.dat[phase_d];
        ctrl_gt vq_err = vac->vdq_ref.dat[phase_q] - vac->vdq_meas_mirror.dat[phase_q];

        vac->idq_set_out.dat[phase_d] = ctl_step_pid_ser(&vac->pid_vd, vd_err);
        vac->idq_set_out.dat[phase_q] = ctl_step_pid_ser(&vac->pid_vq, vq_err);

        ctrl_gt id_ref = vac->idq_set_out.dat[phase_d];
        ctrl_gt iq_ref = vac->idq_set_out.dat[phase_q];
        ctrl_gt i_mag_sq = ctl_mul(id_ref, id_ref) + ctl_mul(iq_ref, iq_ref);

        if (i_mag_sq > vac->max_i2_mag)
        {
            ctrl_gt scaler = ctl_sqrt(ctl_div(vac->max_i2_mag, i_mag_sq));
            vac->idq_set_out.dat[phase_d] = ctl_mul(scaler, id_ref);
            vac->idq_set_out.dat[phase_q] = ctl_mul(scaler, iq_ref);
            ctl_pid_clamping_correction_using_real_output(&vac->pid_vd, vac->idq_set_out.dat[phase_d]);
            ctl_pid_clamping_correction_using_real_output(&vac->pid_vq, vac->idq_set_out.dat[phase_q]);
        }
    }
    else
    {
        ctl_vector2_clear(&vac->idq_set_out);
    }
}

GMP_STATIC_INLINE void ctl_enable_gfl_vac_ctrl(gfl_vac_ctrl_t* vac)
{
    vac->flag_enable = 1;
}

GMP_STATIC_INLINE void ctl_disable_gfl_vac_ctrl(gfl_vac_ctrl_t* vac)
{
    vac->flag_enable = 0;
    ctl_clear_gfl_vac(vac);
}

#ifdef __cplusplus
}
#endif

#endif // _FILE_GFL_VAC_CTRL_H_
